package org.sakaiproject.search.indexing;

import java.io.Serializable;
import java.util.Date;

/**
 * Task created whenever a new operation related to the index occurs.
 * <p>
 * A task contains the minimal amount of information that will be used when executed by a {@link TaskHandler}.
 * </p>
 *
 * @author Colin Hebert
 */
public interface Task extends Serializable {
    /**
     * Obtains the type of the task.
     * <p>
     * The type of a task allows to determine which action should be executed.<br />
     * Tasks are stringly typed to allow an easier creation of custom tasks. It is recommended to create constants or
     * use an enumeration during the instantiation of a Task to avoid potential typos.
     * </p>
     *
     * @return the type of the current task.
     */
    String getType();

    /**
     * Gets a property attached to a task.
     * <p>
     * It's possible to attach properties (as strings) to tasks to allow parametrised tasks.<br />
     * It is recommended to keep property names as constants to avoid potential typos.
     * </p>
     *
     * @param name name of the property to retrieve.
     * @return the value of the given property or null if there is no value to get.
     */
    String getProperty(String name);

    /**
     * Gets the creation date of the task.
     * <p>
     * The creation date of a task can be used to reorder tasks and make sure that the modifications generated by a task
     * created earlier won't override the modifications of a later task.
     * </p>
     *
     * @return the exact date of creation of the current task.
     */
    Date getCreationDate();
}
