package uk.ac.ox.oucs.vle;
// Generated Aug 17, 2010 10:15:40 AM by Hibernate Tools 3.2.2.GA


import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

/**
 * CourseGroupDAO generated by hbm2java
 */
public class CourseGroupDAO  implements java.io.Serializable {


     private String id;
     private String title;
     private String dept;
     private String administrator;
     private Set<CourseComponentDAO> components = new HashSet<CourseComponentDAO>(0);
     private Set<CourseSignupDAO> signups = new HashSet<CourseSignupDAO>(0);
     private Map<String,String> properties = new HashMap<String,String>(0);

    public CourseGroupDAO() {
    }

	
    public CourseGroupDAO(String id) {
        this.id = id;
    }
    public CourseGroupDAO(String id, String title, String dept, String administrator, Set<CourseComponentDAO> components, Set<CourseSignupDAO> signups, Map<String,String> properties) {
       this.id = id;
       this.title = title;
       this.dept = dept;
       this.administrator = administrator;
       this.components = components;
       this.signups = signups;
       this.properties = properties;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDept() {
        return this.dept;
    }
    
    public void setDept(String dept) {
        this.dept = dept;
    }
    public String getAdministrator() {
        return this.administrator;
    }
    
    public void setAdministrator(String administrator) {
        this.administrator = administrator;
    }
    public Set<CourseComponentDAO> getComponents() {
        return this.components;
    }
    
    public void setComponents(Set<CourseComponentDAO> components) {
        this.components = components;
    }
    public Set<CourseSignupDAO> getSignups() {
        return this.signups;
    }
    
    public void setSignups(Set<CourseSignupDAO> signups) {
        this.signups = signups;
    }
    public Map<String,String> getProperties() {
        return this.properties;
    }
    
    public void setProperties(Map<String,String> properties) {
        this.properties = properties;
    }




}


