package uk.ac.ox.oucs.vle;
// Generated Aug 17, 2010 10:15:40 AM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import uk.ac.ox.oucs.vle.CourseSignupService.Status;

/**
 * CourseSignupDAO generated by hbm2java
 */
public class CourseSignupDAO  implements java.io.Serializable {


     private String id;
     private String userId;
     private CourseSignupService.Status status;
     private Date created;
     private Set<CourseComponentDAO> components = new HashSet<CourseComponentDAO>(0);
     private String supervisorId;
     private CourseGroupDAO group;
     private String message;

    public CourseSignupDAO() {
    }

	
    public CourseSignupDAO(String userId) {
        this.userId = userId;
    }
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public CourseSignupService.Status getStatus() {
        return this.status;
    }
    
    public void setStatus(CourseSignupService.Status status) {
        this.status = status;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Set<CourseComponentDAO> getComponents() {
        return this.components;
    }
    
    public void setComponents(Set<CourseComponentDAO> components) {
        this.components = components;
    }
    public String getSupervisorId() {
        return this.supervisorId;
    }
    
    public void setSupervisorId(String supervisorId) {
        this.supervisorId = supervisorId;
    }
    public CourseGroupDAO getGroup() {
        return this.group;
    }
    
    public void setGroup(CourseGroupDAO group) {
        this.group = group;
    }


	public String getMessage() {
		return message;
	}


	public void setMessage(String message) {
		this.message = message;
	}


}


