package org.sakaiproject.citation.impl.soloapi;

/**
 * These are some example Solo APIs generated by Primo for different types.
 * All of them don't specify what format they are in.
 * 
 * @author nickwilson
 * 
 */
public interface SampleSoloApiURLs {

	String SOLO_API_EXAMPLE = "rft_id=oxfaleph017140770";
	String SOLO_API_EXAMPLE_2 = "rft_id=oxfaleph011462895";
	String TEXT = "rft_id=TN_cambridgeS1047951110000326";
	String BOOK = "?rft_id=oxfaleph016633959";
	String ANOTHER_BOOK = "?rft_id=oxfaleph011277642";
	String YET_ANOTHER_BOOK = "?rft_id=oxfaleph012764388";
	String NOT_ANOTHER_BOOK = "?rft_id=oxfaleph017140770";
	String REVIEW = "rft_id=TN_cambridgeS0307883306002653";
	String JOURNAL = "rft_id=oxfaleph017236993";
	String LEGAL = "rft_id=oxfaleph016046673";
	String DISSERTATION = "rft_id=TN_cambridgeS002205070004821X";
	String IMAGE = "rft_id=artstorARHIZOMEIG_10313507317";
	String ANOTHER_IMAGE = "rft_id=oxfaleph020302996";
	String ARTICLE = "rft_id=TN_sciversesciencedirect_elsevier0026-0657(92)91523-M";
	String NEWSPAPER = "rft_id=oxfaleph011255518";
	String OTHER = "rft_id=TN_scopus2-s2.0-0032709626";
	String CORRECT_JOURNAL = "rft_id=oxfaleph015147564";
}
